name = "bfstats"
main = "./index.ts"
compatibility_date = "2022-05-16"

kv_namespaces = [
  { binding = "DATA", id = "c53bec558ffc4485b49260392e1adab2", preview_id = "c53bec558ffc4485b49260392e1adab2" }
]