name = "bfstats"
main = "src/index.ts"
compatibility_date = "2023-07-24"

d1_databases = [
  { binding = "DB", database_name = "bfstats-new", database_id = "e68dccd4-7bf7-4860-ba18-17978966ec10", preview_database_id = "e68dccd4-7bf7-4860-ba18-17978966ec10", migrations_dir = "./src/db/migrations" },
]

# r2_buckets = [
#   { binding = "BUCKET", bucket_name = "d1-backups", preview_bucket_name = "d1-backups" },
# ]

[observability]
enabled = true
