name = "bfstats"
main = "src/index.ts"
compatibility_date = "2024-04-03"

d1_databases = [
  { binding = "DB", database_name = "bfstats-new", database_id = "e68dccd4-7bf7-4860-ba18-17978966ec10", preview_database_id = "e68dccd4-7bf7-4860-ba18-17978966ec10", migrations_dir = "./src/db/migrations" },
]

durable_objects.bindings = [
  { name = "USER_DO", class_name = "UserDurableObject" }
]

migrations = [
  { tag = "v1", new_classes = ["UserDurableObject"] },
  { tag = "v2", deleted_classes = ["UserDurableObject"] },
  { tag = "v3", new_sqlite_classes = ["UserDurableObject"] }
]

# r2_buckets = [
#   { binding = "BUCKET", bucket_name = "d1-backups", preview_bucket_name = "d1-backups" },
# ]

[observability]
enabled = true
